[build]
  base = "."
  command = "npm install -g mystmd && myst build --html"
  publish = "_build/html"

[[redirects]]
  from = "/build/*"
  to = "https://eds-book.netlify.app/build/:splat"
  status = 200
  force = false
